/**
 * tests/test_generate_routing_table.js
 * node --test tests/test_generate_routing_table.js
 *
 * Regression coverage for #154: an unknown CLI flag used to be silently consumed as a
 * positional configPath argument, so loadRoutingRules() would fail to read a real config,
 * return [], and generate() would unconditionally overwrite jarvis.md with an EMPTY routing
 * table (all 7 rules wiped, reproduced live). This suite locks in the fix: strict flag
 * allowlisting, refusal to write when rules.length === 0, and a --check dry-run mode.
 */

import { describe, it, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOOL = join(__dirname, '..', 'tools', 'generate-routing-table.js');

const { generate, parseArgs, EmptyRoutingRulesError, renderTable, spliceTable } =
  await import(pathToFileURL(TOOL).href);

const VALID_CONFIG = [
  '# id | regex | agentShort | command | hintDisplay | keywordsDisplay',
  'backend | \\b(api|service)\\b | Ultron | claude @ultron | backend hint | api, service',
].join('\n');

const JARVIS_TEMPLATE = [
  '# Jarvis',
  '',
  '| Task signal | Route to | Command |',
  '|---|---|---|',
  '<!-- ROUTING_TABLE:START (generated by tools/generate-routing-table.js from config/routing.yml — do not edit rows below by hand) -->',
  '<!-- ROUTING_TABLE:END -->',
  '',
  'trailer text',
].join('\n');

let dir;
let configPath;
let jarvisPath;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'routing-table-test-'));
  configPath = join(dir, 'routing.yml');
  jarvisPath = join(dir, 'jarvis.md');
  writeFileSync(configPath, VALID_CONFIG, 'utf8');
  writeFileSync(jarvisPath, JARVIS_TEMPLATE, 'utf8');
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe('generate() library API', () => {
  it('writes the table when rules are found', () => {
    const result = generate(configPath, jarvisPath);
    assert.equal(result.rulesCount, 1);
    const content = readFileSync(jarvisPath, 'utf8');
    assert.match(content, /Ultron/);
  });

  it('refuses to write when the config yields zero rules (#154 regression)', () => {
    const emptyConfigPath = join(dir, 'empty.yml');
    writeFileSync(emptyConfigPath, '# no rules here\n', 'utf8');
    const before = readFileSync(jarvisPath, 'utf8');

    assert.throws(
      () => generate(emptyConfigPath, jarvisPath),
      EmptyRoutingRulesError
    );

    const after = readFileSync(jarvisPath, 'utf8');
    assert.equal(after, before, 'jarvis.md must be untouched when 0 rules are loaded');
  });

  it('refuses to write when the config path does not exist at all (#154 regression)', () => {
    const bogusPath = join(dir, 'does-not-exist.yml');
    const before = readFileSync(jarvisPath, 'utf8');

    assert.throws(() => generate(bogusPath, jarvisPath), EmptyRoutingRulesError);

    const after = readFileSync(jarvisPath, 'utf8');
    assert.equal(after, before);
  });

  it('--check / dryRun mode does not write to disk', () => {
    const before = readFileSync(jarvisPath, 'utf8');
    const result = generate(configPath, jarvisPath, { dryRun: true });
    const after = readFileSync(jarvisPath, 'utf8');
    assert.equal(after, before, 'dry run must not modify the file');
    assert.equal(result.changed, true);
  });
});

describe('parseArgs()', () => {
  it('accepts known flags', () => {
    const flags = parseArgs(['--check', '--config', '/tmp/a.yml', '--jarvis-md', '/tmp/b.md']);
    assert.equal(flags.check, true);
    assert.equal(flags.config, '/tmp/a.yml');
    assert.equal(flags.jarvisMd, '/tmp/b.md');
  });

  it('rejects an unknown flag instead of silently consuming it as a path (#154 root cause)', () => {
    assert.throws(() => parseArgs(['--forc']), /Unknown flag/);
  });

  it('rejects --config with no value', () => {
    assert.throws(() => parseArgs(['--config']), /requires a path/);
  });
});

describe('CLI process behavior', () => {
  it('exits 2 with usage on an unknown flag, and does not touch jarvis.md', () => {
    const before = readFileSync(jarvisPath, 'utf8');
    assert.throws(() => {
      execFileSync('node', [TOOL, '--forc', configPath, jarvisPath], { encoding: 'utf8', stdio: 'pipe' });
    }, (err) => {
      assert.equal(err.status, 2);
      return true;
    });
    assert.equal(readFileSync(jarvisPath, 'utf8'), before);
  });

  it('exits 1 and does not write when rules.length === 0', () => {
    const emptyConfigPath = join(dir, 'empty.yml');
    writeFileSync(emptyConfigPath, '# no rules\n', 'utf8');
    const before = readFileSync(jarvisPath, 'utf8');
    assert.throws(() => {
      execFileSync('node', [TOOL, '--config', emptyConfigPath, '--jarvis-md', jarvisPath], { encoding: 'utf8', stdio: 'pipe' });
    }, (err) => {
      assert.equal(err.status, 1);
      return true;
    });
    assert.equal(readFileSync(jarvisPath, 'utf8'), before);
  });

  it('exits 0 and writes on success', () => {
    execFileSync('node', [TOOL, '--config', configPath, '--jarvis-md', jarvisPath], { encoding: 'utf8', stdio: 'pipe' });
    assert.match(readFileSync(jarvisPath, 'utf8'), /Ultron/);
  });

  it('--check exits 1 when out of date, 0 when up to date, without writing', () => {
    const beforeContent = readFileSync(jarvisPath, 'utf8');
    assert.throws(() => {
      execFileSync('node', [TOOL, '--check', '--config', configPath, '--jarvis-md', jarvisPath], { encoding: 'utf8', stdio: 'pipe' });
    }, (err) => {
      assert.equal(err.status, 1);
      return true;
    });
    assert.equal(readFileSync(jarvisPath, 'utf8'), beforeContent, '--check must never write');

    // Now actually write, then --check again should be exit 0 (up to date).
    execFileSync('node', [TOOL, '--config', configPath, '--jarvis-md', jarvisPath], { encoding: 'utf8', stdio: 'pipe' });
    const out = execFileSync('node', [TOOL, '--check', '--config', configPath, '--jarvis-md', jarvisPath], { encoding: 'utf8', stdio: 'pipe' });
    assert.match(out, /up to date/);
  });
});

describe('renderTable / spliceTable (pure helpers, unchanged behavior)', () => {
  it('renders one row per rule', () => {
    const rules = [{ keywordsDisplay: 'api', agentShort: 'Ultron', command: 'claude @ultron' }];
    assert.equal(renderTable(rules), '  | api | **Ultron** | `claude @ultron` |');
  });

  it('splices between markers when present', () => {
    const out = spliceTable(JARVIS_TEMPLATE, 'ROWBODY');
    assert.match(out, /ROWBODY/);
  });
});
